// <auto-generated />
using System;
using FITSKIP.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FITSKIP.Infrastructure.Migrations
{
    [DbContext(typeof(FitskipDbContext))]
    [Migration("20251026112236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ManagerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCDAEAF02C2");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<DateOnly?>("DateUse")
                        .HasColumnType("date");

                    b.Property<string>("EquipmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Qrcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QRCode");

                    b.Property<int?>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.Property<int?>("Yom")
                        .HasColumnType("int")
                        .HasColumnName("YOM");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__34474599BD4FBDFE");

                    b.HasIndex("StageId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.IncidentHistory", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IncidentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<bool>("IsTechSupport")
                        .HasColumnType("bit");

                    b.Property<string>("Issue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("IncidentId")
                        .HasName("PK__Incident__5F46CAB00C9D9F0A");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("TypeId");

                    b.ToTable("IncidentHistory", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.IncidentShift", b =>
                {
                    b.Property<int>("IncidentShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IncidentShiftID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentShiftId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentID");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("IncidentShiftId")
                        .HasName("PK__IncidentShift__IncidentShiftID");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("IncidentShifts", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LineId")
                        .HasName("PK__Lines__2EAE64C9765DBF83");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenanceChecklistItem", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChecklistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ChecklistId")
                        .HasName("PK__Maintena__26C4E2F5A1234567");

                    b.HasIndex("PlanId");

                    b.ToTable("MaintenanceChecklistItems");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenancePlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<string>("IntervalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PlanId")
                        .HasName("PK__Maintena__755C22D75A5E8C31");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("EquipmentId");

                    b.ToTable("MaintenancePlans");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notification__NotificationID");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ProductionOutput", b =>
                {
                    b.Property<int>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OutputID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutputId"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("GoodQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("IdealCycleTime")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<int>("PlannedProductionTime")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.Property<decimal>("TargetQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OutputId")
                        .HasName("PK__Producti__CE7609460B69FF1F");

                    b.HasIndex("LineId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ProductionOutputs");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RequestId")
                        .HasName("PK__Purchase__33A8519A9AC26C34");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("PartId");

                    b.HasIndex("RejectedBy");

                    b.HasIndex("RequestedBy");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ReplacementHistory", b =>
                {
                    b.Property<int>("ReplacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReplacementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplacementId"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReplacedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReplacedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReplacementId")
                        .HasName("PK__Replacem__55AB07E93456789A");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PartId");

                    b.HasIndex("ReplacedBy");

                    b.ToTable("ReplacementHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId")
                        .HasName("PK__Shifts__C0A838E1E127179C");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.SparePart", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReplacementCycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specifications")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Supplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UoM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Warehouse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PartId")
                        .HasName("PK__SparePar__7C3F0D30890EDD23");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StageId")
                        .HasName("PK__Stages__03EB7AF84C50ECAB");

                    b.HasIndex("LineId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.StopType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TypeId")
                        .HasName("PK__StopType__516F0395AE2FC0CE");

                    b.ToTable("StopType", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.UserLine", b =>
                {
                    b.Property<int>("UserLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLineId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserLineId")
                        .HasName("PK__UserLine__3B1F2081CE44FE03");

                    b.HasIndex("LineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLines");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Departmen__Manag__619B8048");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .HasConstraintName("FK__Equipment__Stage__70DDC3D8");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.IncidentHistory", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__IncidentH__Equip__7B5B524B");

                    b.HasOne("FITSKIP.Domain.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId");

                    b.HasOne("FITSKIP.Domain.Entities.StopType", "Type")
                        .WithMany("IncidentHistories")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__IncidentH__TypeI__7F2BE32F");

                    b.Navigation("Equipment");

                    b.Navigation("ReportedByUser");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.IncidentShift", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.IncidentHistory", "Incident")
                        .WithMany("IncidentShifts")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IncidentShift_IncidentHistory_IncidentID");

                    b.HasOne("FITSKIP.Domain.Entities.Shift", "Shift")
                        .WithMany("IncidentShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("FK_IncidentShift_Shifts_ShiftID");

                    b.Navigation("Incident");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Department", "Department")
                        .WithMany("Lines")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Lines__Departmen__6A30C650");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenanceChecklistItem", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.MaintenancePlan", "Plan")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintena__PlanID__3456789");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenancePlan", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__MaintenanPlan__User__2345678");

                    b.HasOne("FITSKIP.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__MaintenanPlan__Equip__1234567");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notifications_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ProductionOutput", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("ProductionOutputs")
                        .HasForeignKey("LineId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__LineI__08B54D69");

                    b.HasOne("FITSKIP.Domain.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__ShiftID__0A9D95DB");

                    b.Navigation("Line");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("PurchaseRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__PurchaseR__Appro__151B244E");

                    b.HasOne("FITSKIP.Domain.Entities.SparePart", "Part")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("PartId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseR__PartI__1332DBDC");

                    b.HasOne("FITSKIP.Domain.Entities.User", "RejectedByNavigation")
                        .WithMany("PurchaseRequestRejectedByNavigations")
                        .HasForeignKey("RejectedBy")
                        .HasConstraintName("FK__PurchaseR__Rejec__151B245F");

                    b.HasOne("FITSKIP.Domain.Entities.User", "RequestedByNavigation")
                        .WithMany("PurchaseRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseR__Reque__14270015");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Part");

                    b.Navigation("RejectedByNavigation");

                    b.Navigation("RequestedByNavigation");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ReplacementHistory", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__Replaceme__Equip__4567890A");

                    b.HasOne("FITSKIP.Domain.Entities.SparePart", "Part")
                        .WithMany("ReplacementHistories")
                        .HasForeignKey("PartId")
                        .IsRequired()
                        .HasConstraintName("FK__Replaceme__PartI__5678901B");

                    b.HasOne("FITSKIP.Domain.Entities.User", "ReplacedByNavigation")
                        .WithMany("ReplacementHistories")
                        .HasForeignKey("ReplacedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Replaceme__Repla__6789012C");

                    b.Navigation("Equipment");

                    b.Navigation("Part");

                    b.Navigation("ReplacedByNavigation");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Stage", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("Stages")
                        .HasForeignKey("LineId")
                        .HasConstraintName("FK__Stages__LineID__6D0D32F4");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.User", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AspNetUsers_Departments_DepartmentId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AspNetUsers_AspNetRoles_RoleId");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.UserLine", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("UserLines")
                        .HasForeignKey("LineId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLines__LineI__03F0984C");

                    b.HasOne("FITSKIP.Domain.Entities.User", "User")
                        .WithMany("UserLines")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLines__UserI__02FC7413");

                    b.Navigation("Line");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.IncidentHistory", b =>
                {
                    b.Navigation("IncidentShifts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.Navigation("ProductionOutputs");

                    b.Navigation("Stages");

                    b.Navigation("UserLines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenancePlan", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Shift", b =>
                {
                    b.Navigation("IncidentShifts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.SparePart", b =>
                {
                    b.Navigation("PurchaseRequests");

                    b.Navigation("ReplacementHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.StopType", b =>
                {
                    b.Navigation("IncidentHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.User", b =>
                {
                    b.Navigation("PurchaseRequestApprovedByNavigations");

                    b.Navigation("PurchaseRequestRejectedByNavigations");

                    b.Navigation("PurchaseRequestRequestedByNavigations");

                    b.Navigation("ReplacementHistories");

                    b.Navigation("UserLines");
                });
#pragma warning restore 612, 618
        }
    }
}
