// <auto-generated />
using System;
using FITSKIP.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FITSKIP.Infrastructure.Migrations
{
    [DbContext(typeof(FitskipDbContext))]
    partial class FitskipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCDAEAF02C2");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<DateOnly?>("DateUse")
                        .HasColumnType("date");

                    b.Property<string>("EquipmentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("Origin")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Qrcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QRCode");

                    b.Property<int?>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.Property<int?>("Yom")
                        .HasColumnType("int")
                        .HasColumnName("YOM");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__34474599BD4FBDFE");

                    b.HasIndex("LineId");

                    b.HasIndex("StageId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ErrorHistory", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ErrorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorId"));

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("ErrorId")
                        .HasName("PK__ErrorHis__358565CA8E27F35E");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LineId");

                    b.HasIndex("SlotId");

                    b.HasIndex("StageId");

                    b.HasIndex("TypeId");

                    b.ToTable("ErrorHistory", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.GroupLine", b =>
                {
                    b.Property<int>("GroupLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupLineId"));

                    b.Property<string>("GroupLineName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.HasKey("GroupLineId")
                        .HasName("PK__GroupLin__23A523FB9505A5CE");

                    b.HasIndex("RoomId");

                    b.ToTable("GroupLines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineId"));

                    b.Property<int?>("GroupLineId")
                        .HasColumnType("int")
                        .HasColumnName("GroupLineID");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LineId")
                        .HasName("PK__Lines__2EAE64C9765DBF83");

                    b.HasIndex("GroupLineId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenanceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ErrorId")
                        .HasColumnType("int")
                        .HasColumnName("ErrorID");

                    b.Property<string>("ResolutionDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TechnicianID");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Maintena__32499E57A8B16523");

                    b.HasIndex("ErrorId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceAssignments");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ProductionOutput", b =>
                {
                    b.Property<int>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OutputID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutputId"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.Property<int>("StageId")
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    b.HasKey("OutputId")
                        .HasName("PK__Producti__CE7609460B69FF1F");

                    b.HasIndex("LineId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("StageId");

                    b.ToTable("ProductionOutputs");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Urgency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Normal");

                    b.HasKey("RequestId")
                        .HasName("PK__Purchase__33A8519A9AC26C34");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("PartId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__3286391944F5E5E2");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId")
                        .HasName("PK__Shifts__C0A838E1E127179C");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ShiftSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("ShiftID");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId")
                        .HasName("PK__ShiftSlo__0A124A4FF4CC8D65");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftSlots");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.SparePart", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.HasKey("PartId")
                        .HasName("PK__SparePar__7C3F0D30890EDD23");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageId"));

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StageId")
                        .HasName("PK__Stages__03EB7AF84C50ECAB");

                    b.HasIndex("LineId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.StopType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TypeId")
                        .HasName("PK__StopType__516F0395AE2FC0CE");

                    b.ToTable("StopType", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.UserLine", b =>
                {
                    b.Property<int>("UserLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLineId"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserLineId")
                        .HasName("PK__UserLine__3B1F2081CE44FE03");

                    b.HasIndex("LineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLines");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "Manager")
                        .WithMany("Departments")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK__Departmen__Manag__619B8048");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("Equipment")
                        .HasForeignKey("LineId")
                        .HasConstraintName("FK__Equipment__LineI__71D1E811");

                    b.HasOne("FITSKIP.Domain.Entities.Stage", "Stage")
                        .WithMany("Equipment")
                        .HasForeignKey("StageId")
                        .HasConstraintName("FK__Equipment__Stage__70DDC3D8");

                    b.Navigation("Line");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ErrorHistory", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__ErrorHist__Equip__7B5B524B");

                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("LineId")
                        .HasConstraintName("FK__ErrorHist__LineI__7D439ABD");

                    b.HasOne("FITSKIP.Domain.Entities.ShiftSlot", "Slot")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK__ErrorHist__SlotI__7E37BEF6");

                    b.HasOne("FITSKIP.Domain.Entities.Stage", "Stage")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("StageId")
                        .HasConstraintName("FK__ErrorHist__Stage__7C4F7684");

                    b.HasOne("FITSKIP.Domain.Entities.StopType", "Type")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__ErrorHist__TypeI__7F2BE32F");

                    b.Navigation("Equipment");

                    b.Navigation("Line");

                    b.Navigation("Slot");

                    b.Navigation("Stage");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.GroupLine", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Room", "Room")
                        .WithMany("GroupLines")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__GroupLine__RoomI__6754599E");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.GroupLine", "GroupLine")
                        .WithMany("Lines")
                        .HasForeignKey("GroupLineId")
                        .HasConstraintName("FK__Lines__GroupLine__6A30C649");

                    b.Navigation("GroupLine");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.MaintenanceAssignment", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.ErrorHistory", "Error")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("ErrorId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Error__18EBB532");

                    b.HasOne("FITSKIP.Domain.Entities.User", "Technician")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("TechnicianId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Techn__19DFD96B");

                    b.Navigation("Error");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ProductionOutput", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("ProductionOutputs")
                        .HasForeignKey("LineId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__LineI__08B54D69");

                    b.HasOne("FITSKIP.Domain.Entities.Shift", "Shift")
                        .WithMany("ProductionOutputs")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__Shift__0A9D95DB");

                    b.HasOne("FITSKIP.Domain.Entities.Stage", "Stage")
                        .WithMany("ProductionOutputs")
                        .HasForeignKey("StageId")
                        .IsRequired()
                        .HasConstraintName("FK__Productio__Stage__09A971A2");

                    b.Navigation("Line");

                    b.Navigation("Shift");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("PurchaseRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK__PurchaseR__Appro__151B244E");

                    b.HasOne("FITSKIP.Domain.Entities.SparePart", "Part")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("PartId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseR__PartI__1332DBDC");

                    b.HasOne("FITSKIP.Domain.Entities.User", "RequestedByNavigation")
                        .WithMany("PurchaseRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseR__Reque__14270015");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Part");

                    b.Navigation("RequestedByNavigation");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Room", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Rooms__Departmen__6477ECF3");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ShiftSlot", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftSlots")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("FK__ShiftSlot__Shift__76969D2E");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Stage", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("Stages")
                        .HasForeignKey("LineId")
                        .HasConstraintName("FK__Stages__LineID__6D0D32F4");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.UserLine", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.Line", "Line")
                        .WithMany("UserLines")
                        .HasForeignKey("LineId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLines__LineI__03F0984C");

                    b.HasOne("FITSKIP.Domain.Entities.User", "User")
                        .WithMany("UserLines")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLines__UserI__02FC7413");

                    b.Navigation("Line");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FITSKIP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FITSKIP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Department", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("ErrorHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ErrorHistory", b =>
                {
                    b.Navigation("MaintenanceAssignments");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.GroupLine", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Line", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("ErrorHistories");

                    b.Navigation("ProductionOutputs");

                    b.Navigation("Stages");

                    b.Navigation("UserLines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Room", b =>
                {
                    b.Navigation("GroupLines");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Shift", b =>
                {
                    b.Navigation("ProductionOutputs");

                    b.Navigation("ShiftSlots");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.ShiftSlot", b =>
                {
                    b.Navigation("ErrorHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.SparePart", b =>
                {
                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.Stage", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("ErrorHistories");

                    b.Navigation("ProductionOutputs");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.StopType", b =>
                {
                    b.Navigation("ErrorHistories");
                });

            modelBuilder.Entity("FITSKIP.Domain.Entities.User", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("MaintenanceAssignments");

                    b.Navigation("PurchaseRequestApprovedByNavigations");

                    b.Navigation("PurchaseRequestRequestedByNavigations");

                    b.Navigation("UserLines");
                });
#pragma warning restore 612, 618
        }
    }
}
